<?php
define(PAYPAL_CLIENT_ID, 'Aa8DIY3d0AJNLf1QHEMC8u7NzMPEtrZf5DTnT-JLamZywcd7fLqQv4XoYMvG0ygCh5EBVYrZym4XaZB-');
define(PAYPAL_SECRET, 'EE-rwwpkHBAtZ1HzC41ewNfAViMy85ISX-1daaA6-eE5cdFMTizy6YLLtzwVYjAGRPJid-Cyv_Ujf_I2');
